-- ===================================================================
-- SmartSchool - Initial Database Schema (Fully Aligned with FRS)
-- Version: 1
-- Description: Creates all base tables, enums, and constraints for the School Management System.
-- ===================================================================

-- It's good practice to enable required extensions if any.
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ===================================================================
-- 1. CORE SETUP & CONFIGURATION TABLES
-- ===================================================================

-- Table to define academic sessions (e.g., 2024-2025)
CREATE TABLE academic_sessions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_current BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to define classes (e.g., Grade 1, Grade 2)
CREATE TABLE classes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to define sections within a class (e.g., A, B, C)
CREATE TABLE sections (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(10) NOT NULL,
    class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(class_id, name) -- A section name must be unique within a class
);

-- Table to define subjects
CREATE TABLE subjects (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(20) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Junction table to link subjects to classes
CREATE TABLE class_subjects (
    class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    PRIMARY KEY (class_id, subject_id)
);


-- ===================================================================
-- 2. USER & PERSONNEL MANAGEMENT TABLES
-- ===================================================================

-- Central table for all people (students, staff, parents)
CREATE TABLE persons (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    cnic VARCHAR(15) UNIQUE,
    date_of_birth DATE,
    gender VARCHAR(10) CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    address TEXT,
    primary_contact VARCHAR(20),
    secondary_contact VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    photo_path VARCHAR(512), -- Path to the stored profile picture
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table for application users (login credentials)
CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, -- Will be hashed (e.g., BCrypt)
    role VARCHAR(50) NOT NULL CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'TEACHER', 'ACCOUNTANT', 'PARENT')),
    person_id BIGINT UNIQUE REFERENCES persons(id) ON DELETE CASCADE,
    is_enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table for Staff (extends Persons)
CREATE TABLE staff (
    id BIGINT PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    employee_id VARCHAR(50) UNIQUE NOT NULL,
    joining_date DATE NOT NULL,
    basic_salary DECIMAL(10, 2),
    designation VARCHAR(100)
);

-- Table for payroll deduction types (e.g., Tax, Insurance)
CREATE TABLE deduction_types (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_percentage BOOLEAN DEFAULT FALSE, -- If true, 'amount' is a percentage
    amount DECIMAL(10, 2) NOT NULL, -- Value or percentage
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to store generated payroll records (payslips)
CREATE TABLE payroll_records (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    staff_id BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    basic_salary DECIMAL(10, 2) NOT NULL,
    total_deductions DECIMAL(10, 2) DEFAULT 0.00,
    net_salary DECIMAL(10, 2) NOT NULL,
    generated_by_user_id BIGINT NOT NULL REFERENCES users(id),
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(staff_id, month, year)
);

-- Table to store individual deductions for a payroll record
CREATE TABLE payroll_deductions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payroll_record_id BIGINT NOT NULL REFERENCES payroll_records(id) ON DELETE CASCADE,
    deduction_type_id BIGINT NOT NULL REFERENCES deduction_types(id),
    deduction_amount DECIMAL(10, 2) NOT NULL
);

-- Junction table to assign teachers to classes and subjects
CREATE TABLE teacher_assignments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    staff_id BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    academic_session_id BIGINT NOT NULL REFERENCES academic_sessions(id) ON DELETE CASCADE,
    UNIQUE(staff_id, class_id, subject_id, academic_session_id) -- A teacher can only be assigned once to a specific subject in a class for a session
);


-- ===================================================================
-- 3. STUDENT MANAGEMENT TABLES
-- ===================================================================

-- Table for Students (extends Persons)
CREATE TABLE students (
    id BIGINT PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    admission_number VARCHAR(50) UNIQUE NOT NULL,
    b_form_number VARCHAR(30) UNIQUE,
    admission_date DATE NOT NULL
);

-- Junction table for student enrollment in a specific class/section for a session
CREATE TABLE student_enrollments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    section_id BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    academic_session_id BIGINT NOT NULL REFERENCES academic_sessions(id) ON DELETE CASCADE,
    roll_number INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, academic_session_id) -- A student can have only one enrollment per session
);

-- Table to link students to their parents/guardians
CREATE TABLE student_guardians (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    guardian_id BIGINT NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    relation VARCHAR(50) NOT NULL, -- e.g., 'FATHER', 'MOTHER', 'UNCLE'
    is_primary BOOLEAN DEFAULT FALSE,
    UNIQUE(student_id, guardian_id)
);


-- ===================================================================
-- 4. ACADEMIC & ATTENDANCE TABLES
-- ===================================================================

-- Table for attendance records
CREATE TABLE attendance (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PRESENT', 'ABSENT', 'ON_LEAVE')),
    remarks TEXT,
    marked_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, attendance_date) -- A student can have only one attendance record per day
);

-- Table for examination terms
CREATE TABLE exam_terms (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL, -- e.g., 'Mid-Term', 'Final'
    academic_session_id BIGINT NOT NULL REFERENCES academic_sessions(id) ON DELETE CASCADE,
    start_date DATE,
    end_date DATE,
    is_published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table for storing student marks
CREATE TABLE marks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    exam_term_id BIGINT NOT NULL REFERENCES exam_terms(id) ON DELETE CASCADE,
    obtained_marks DECIMAL(5, 2),
    max_marks DECIMAL(5, 2),
    grade CHAR(2), -- e.g., 'A+', 'B'
    percentage DECIMAL(5, 2),
    teacher_remarks TEXT, -- For report cards
    updated_by_user_id BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, subject_id, exam_term_id)
);

-- Table for grading scales (aligned with EXM-04, EXM-05)
CREATE TABLE grading_scales (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exam_term_id BIGINT NOT NULL REFERENCES exam_terms(id) ON DELETE CASCADE, -- Grading can vary per exam
    grade_label VARCHAR(10) NOT NULL, -- e.g., 'A+', 'A', 'B'
    min_percentage DECIMAL(5, 2) NOT NULL, -- e.g., 90.00
    max_percentage DECIMAL(5, 2) NOT NULL, -- e.g., 100.00
    remarks VARCHAR(255),
    UNIQUE(exam_term_id, grade_label)
);


-- ===================================================================
-- 5. FEE & FINANCE TABLES
-- ===================================================================

-- Table for fee structures
CREATE TABLE fee_structures (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL, -- e.g., 'Grade 10 Tuition Fee'
    class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE, -- NULL if it's a general fee
    amount DECIMAL(10, 2) NOT NULL,
    is_monthly BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table for discounts
CREATE TABLE discounts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE, -- e.g., 'Sibling Discount'
    percentage DECIMAL(5, 2) NOT NULL, -- e.g., 10.00 for 10%
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to apply discounts to specific students
CREATE TABLE student_discounts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    discount_id BIGINT NOT NULL REFERENCES discounts(id) ON DELETE CASCADE,
    applied_from_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE(student_id, discount_id)
);

-- Table for generated fee vouchers
CREATE TABLE fee_vouchers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    voucher_number VARCHAR(50) UNIQUE NOT NULL,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    due_date DATE NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    total_discount_amount DECIMAL(10, 2) DEFAULT 0.00,
    payable_amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PAID', 'OVERDUE')),
    month INTEGER NOT NULL, -- e.g., 1 for January, 2 for February
    year INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- NEW: Table for itemized fee details (aligned with FEE-06)
CREATE TABLE fee_voucher_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fee_voucher_id BIGINT NOT NULL REFERENCES fee_vouchers(id) ON DELETE CASCADE,
    fee_structure_id BIGINT NOT NULL REFERENCES fee_structures(id),
    amount DECIMAL(10, 2) NOT NULL,
    discount_amount DECIMAL(10, 2) DEFAULT 0.00
);

-- Table for payments made against vouchers
CREATE TABLE payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fee_voucher_id BIGINT NOT NULL REFERENCES fee_vouchers(id) ON DELETE CASCADE,
    amount_paid DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('CASH', 'BANK_TRANSFER', 'ONLINE')),
    payment_date DATE NOT NULL,
    transaction_id VARCHAR(100), -- For bank/online payments
    notes TEXT,
    received_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ===================================================================
-- 6. COMMUNICATION TABLES
-- ===================================================================

-- NEW: Table for SMS templates (aligned with ATT-06, COM-01)
CREATE TABLE sms_templates (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE, -- e.g., 'Student Absenteeism'
    content TEXT NOT NULL, -- e.g., 'Dear Parent, {student_name} was absent from {class_name} on {date}.'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table to log all outgoing SMS
CREATE TABLE sms_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipient_phone VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL, -- e.g., 'SENT', 'FAILED', 'PENDING'
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ===================================================================
-- 7. INDEXES FOR PERFORMANCE
-- ===================================================================

-- Indexes for frequently queried foreign keys and columns
CREATE INDEX idx_users_person_id ON users(person_id);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_students_admission_number ON students(admission_number);
CREATE INDEX idx_attendance_student_date ON attendance(student_id, attendance_date);
CREATE INDEX idx_marks_student_term ON marks(student_id, exam_term_id);
CREATE INDEX idx_fee_vouchers_student ON fee_vouchers(student_id);
CREATE INDEX idx_fee_vouchers_status ON fee_vouchers(status);
CREATE INDEX idx_payments_voucher_id ON payments(fee_voucher_id);
CREATE INDEX idx_student_enrollments_session ON student_enrollments(academic_session_id);


-- ===================================================================
-- 8. TRIGGERS FOR UPDATED_AT
-- ===================================================================

-- A function to update the updated_at column
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$ BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
 $$ LANGUAGE plpgsql;

-- Apply the trigger to all tables with an updated_at column
CREATE TRIGGER set_academic_sessions_timestamp
BEFORE UPDATE ON academic_sessions
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_classes_timestamp
BEFORE UPDATE ON classes
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_sections_timestamp
BEFORE UPDATE ON sections
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_persons_timestamp
BEFORE UPDATE ON persons
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_users_timestamp
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_marks_timestamp
BEFORE UPDATE ON marks
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();
